language: objective-c  #1
osx_image: xcode7.2 #2
xcode_workspace: luxafor-mac.xcworkspace #3
xcode_scheme: Luxa4Mac #4
xcode_sdk: macosx10.11 #5
podfile: Luxa4Mac/Podfile

notifications:
email:
recipients:
- sdevore@sdevore.com
on_success: change # default: change
on_failure: always # default: always