platform :osx, "10.10"

abstract_target 'PivotalTracker' do
    pod "NSColor-Crayola"
    pod "NSColor-Pantone"
    pod "CocoaLumberjack"
    pod "XCDLumberjackNSLogger"
    abstract_target 'Tests' do
        pod 'OHHTTPStubs'
        pod 'OCMock'
    
        target :Luxa4MacTests do
       
        end
    
        target :Luxa4MacXPCTests do
    
        end
    end
    
    target :Luxa4Mac do
        pod "DevMateKit"
    end
   
    
    target :Luxa4MacXPC do
        
    end
end
