platform :osx, "10.10"

pod "NSColor-Crayola"
pod "NSColor-Pantone"
pod "CocoaLumberjack"
pod "XCDLumberjackNSLogger"

target :Luxa4MacTests, :exclusive => true do
  pod 'OHHTTPStubs'
  pod 'OCMock'
end

target :Luxa4Mac, :exclusive => true do
    pod "DevMateKit"
end